steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'allotment-map'
      - '--source'
      - '.'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
